### PR TITLE
Merging the working code for the basic version of the app into the main branch

### PR DESCRIPTION
**Pull request by Zev-G**
Up until this moment, our code has not been clean, and has frequently gotten dirtier, and as such we have chosen to work on the ugly "game" branch.

Now, our code has been refactored to provide a basic, working, minimum example which follows clean architecture and which allows for several of our user stories to be completed.

Here's what **has** been completed:
- The "Main Page" view
- The "Account" view
- The "Game" view
- The ability to play the game and have points scored
- Play with a friend across a network and run a server
- Navigate throughout the UI, from one page to another

What has **not** been completed:
- A complete inclusion of comments for the entire project
- The integration of the backend database
- Several new features which are still being debated in the planning phase of this project
- The "Login", "Signup", "Stats", and "Results" pages and navigation between them
- UI for a multiplayer game
- Uploading images

### CODE REVIEW

**Comment by Tallduoft** [comment]
Looks Great To Me !!

**Review by KristopherZ — APPROVED** [review]
Everything looks OK. However, a lot of comments needed to be added and we also need unit tests for entity and use case. But as of now, I think we should indeed update the main branch to have a fundamental working tree for the later code changes.

**Review by r11creates — APPROVED** [review]
The coding style in this pull request looks consistent and adheres well to clean architecture principles, which ensures maintainability and readability. It's great to see that tests are written for most of the functionality, providing a good foundation for validating the code's correctness. While the absence of Javadocs and inline comments is noted, it doesn't seem to hinder the immediate understanding of the code. However, adding these in the future would further improve the clarity and usability of the code for the team. Overall, this is a strong submission that aligns with our project standards.

**Review by aksshatt7 — APPROVED** [review]
The code is well-formatted,  functionality is mostly correct and finished. Tests cover core functionality. While Clean Architecture and SOLID principles are largely followed, we still need to refactor some parts of the code and add a few use cases.

**Pull request merged**
